site_name: ProBuilder Documentation
# theme_dir: 'themes/readthedocs'
theme: readthedocs
extra_css:
  - css/alerts.css
  - css/extra.css
  - css/general.css
  - css_site/site.css
  - css_site/youtube.css

pages:

- Home: index.md
- Install ProBuilder: upgrading/overview.md
- Fundamentals: general/fundamentals.md

- Toolbar:
  - Overview: toolbar/overview-toolbar.md
  - Tool Windows: toolbar/tool-panels.md
  - Poly Shape: toolbar/polyshape.md
  - Selection Actions: toolbar/selection-tools.md
  - Object Actions: toolbar/object-actions.md
  - Vertex Actions: toolbar/vertex.md
  - Edge Actions: toolbar/edge.md
  - Face Actions: toolbar/face.md
  - Element Actions: toolbar/all.md

- Texture Mapping:
    - Overview: texturing/overview-texture-mapping.md
    - UV Editor Toolbar: texturing/uv-editor-toolbar.md
    - Auto UVs Actions: texturing/auto-uvs-actions.md
    - Manual UVs Actions: texturing/manual-uvs-actions.md

- Menu Actions: general/menu-actions.md
- Experimental: experimental/experimental-overview.md

- Preferences: preferences/preferences.md
- FAQ: troubleshooting/faq.md
- Third-Party Licenses: credits.md
- Changelog: changelog.md
