site_name: ProBuilder Documentation
theme: readthedocs

pages:

- Home: index.md

- Fundamentals: general/fundamentals.md

- Toolbar:
  - Overview: toolbar/overview.md
  - Editors: toolbar/editors.md
  - Selection Tools: toolbar/selection.md
  - Geometry Actions:
    - toolbar/actions/all.md
    - toolbar/actions/object.md
    - toolbar/actions/face.md
    - toolbar/actions/edge.md
    - toolbar/actions/vertex.md

- Troubleshooting:
  - troubleshooting/faq.md

- Upgrading:
  - What Upgrade Procedure Should I Follow?: upgrading/overview.md
  - Standard: upgrading/standard.md
  - DLL Rename: upgrading/dllrename.md
  - Upgrade Kit: upgrading/upgradekit.md
  - Prototype: upgrading/prototypeupgrade.md

