site_name: ProBuilder Documentation
# theme_dir: 'themes/readthedocs'
theme: readthedocs
extra_css:
  - css/alerts.css
  - css/extra.css
  - css/general.css
  - css_site/site.css
  - css_site/youtube.css
extra_javascript:
  - javascript/zendesk-chat.js

pages:

- Home: index.md
- Fundamentals: general/fundamentals.md

- Toolbar:
  - Overview: toolbar/overview-toolbar.md
  - Tool Panels: toolbar/tool-panels.md
  - Selection Actions: toolbar/selection-tools.md
  - Object Actions: toolbar/object-actions.md
  - Vertex Actions: toolbar/vertex.md
  - Edge Actions: toolbar/edge.md
  - Face Actions: toolbar/face.md
  - Element Actions: toolbar/all.md

- Texture Mapping:
    - Overview: texturing/overview-texture-mapping.md
    - UV Editor Toolbar: texturing/uv-editor-toolbar.md
    - Auto UVs Actions: texturing/auto-uvs-actions.md
    - Manual UVs Actions: texturing/manual-uvs-actions.md

- Menu Actions: menu-actions.md

- Preferences: preferences/preferences.md

- Troubleshooting:
  - troubleshooting/faq.md

- Upgrading:
  - What Upgrade Procedure Should I Follow?: upgrading/overview.md
  - Standard: upgrading/standard.md
  - DLL Rename: upgrading/dllrename.md
  - Upgrade Kit: upgrading/upgrade-kit.md
  - Prototype: upgrading/prototype.md

- Credits: credits.md

- Changelog: changelog.md
