site_name: ProBuilder Documentation
theme: readthedocs

pages:

- Home: index.md

- Fundamentals: general/fundamentals.md

- Toolbar: 
  - Overview: toolbar/overview-toolbar.md
  - Tool Panels: toolbar/tool-panels.md
  - Selection Tools: toolbar/selection-tools.md
  - Object Actions: toolbar/object-actions.md
  - Geometry Actions:
    - Vertex: toolbar/vertex.md
    - Edge: toolbar/edge.md
    - Face: toolbar/face.md
    - All: toolbar/all.md
    
- Texturing and UVs: 
    - Overview: texturing/overview-texturing.md
    - Auto-Texturing: texturing/auto-texturing.md
    - Manual UV Editing: texturing/manual-uv-editing.md
    
- Troubleshooting:
  - troubleshooting/faq.md

- Upgrading:
  - What Upgrade Procedure Should I Follow?: upgrading/overview.md
  - Standard: upgrading/standard.md
  - DLL Rename: upgrading/dllrename.md
  - Upgrade Kit: upgrading/upgrade-kit.md
  - Prototype: upgrading/prototype.md

