site_name: ProBuilder Documentation
theme: readthedocs
pages:
- Home: index.md
- Editors:
  - Overview: editors/overview.md
  - Text Toolbar: editors/toolbar_text.md
  - Icon Toolbar: editors/toolbar_icons.md
